// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  indexSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    },
    {
      "type": "link",
      "label": "Benchmarks",
      "href": "/benchmarks"
    },
    {
      "type": "link",
      "label": "API",
      "href": "api"
    },
  ],
};

module.exports = sidebars;
